const SUPABASE_URL='https://okrvklvvulmjdarlwdbl.supabase.co';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJva3J2a2x2dnVsbWpkYXJsd2RibCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzgzOTU4MTkxLCJleHAiOjIwOTk1MzQxOTF9.X8lXu_ZHB1v_tSvQso4RVEWt32NaI7gPZrTlQsB6dog';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const chartZoomEventFix={id:'chartZoomEventFix',beforeEvent(chart,args){const event=args.event,native=event?.native,rect=chart.canvas?.getBoundingClientRect?.();if(!native||!rect?.width||!rect?.height||!Number.isFinite(native.clientX)||!Number.isFinite(native.clientY))return;event.x=(native.clientX-rect.left)*(chart.width/rect.width);event.y=(native.clientY-rect.top)*(chart.height/rect.height)}};
if(window.Chart)Chart.register(chartZoomEventFix);
const RESTRICTED=['miria@misterwiz.com.br','custodio@sforza.com.br'];
const ACTIVE=new Set(['completo','aprovado','paga','faturado','aguardando pagto','pendente','ag. pagamento','boleto impresso','pending','iniciada','aguardando faturamento','atrasado','faturamento atrasado']);
const BASEGERAL_APPROVED=new Set(['aprovado','completo']);
const UF_COORDS={AC:[-9.97,-67.81],AL:[-9.62,-36.82],AP:[.03,-51.05],AM:[-3.10,-60.02],BA:[-12.97,-38.50],CE:[-3.73,-38.52],DF:[-15.79,-47.88],ES:[-20.31,-40.31],GO:[-16.68,-49.25],MA:[-2.53,-44.30],MT:[-15.60,-56.10],MS:[-20.45,-54.62],MG:[-19.92,-43.94],PA:[-1.45,-48.49],PB:[-7.12,-34.86],PR:[-25.43,-49.27],PE:[-8.05,-34.90],PI:[-5.09,-42.80],RJ:[-22.91,-43.17],RN:[-5.79,-35.21],RS:[-30.03,-51.23],RO:[-8.76,-63.90],RR:[2.82,-60.67],SC:[-27.59,-48.55],SP:[-23.55,-46.63],SE:[-10.91,-37.07],TO:[-10.18,-48.33]};
const STATE_NAMES={acre:'AC',alagoas:'AL',amapa:'AP',amazonas:'AM',bahia:'BA',ceara:'CE','distrito federal':'DF','espirito santo':'ES',goias:'GO',maranhao:'MA','mato grosso':'MT','mato grosso do sul':'MS','minas gerais':'MG',para:'PA',paraiba:'PB',parana:'PR',pernambuco:'PE',piaui:'PI','rio de janeiro':'RJ','rio grande do norte':'RN','rio grande do sul':'RS',rondonia:'RO',roraima:'RR','santa catarina':'SC','sao paulo':'SP',sergipe:'SE',tocantins:'TO'};
let rows=[],selectedGroup='ALL',selectedMonth='',dateFrom='',dateTo='',selectedChannel='',selectedSeller='',searchClient='',searchProduct='';
let monthlyChart,dailyChart,weeklyChart,productHistoryChart,leafletMap,leafletLayer,currentUser,goalsMap={},baseCache=null,renderFrame=0,searchTimer=0,mapTask=0;
const expandedComparisonChannels=new Set();
const detailRowStore=new Map(),historyRowStore=new Map();
const el=id=>document.getElementById(id);
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const money=v=>typeof v==='number'?v:(parseFloat(String(v??'0').replace(/[^0-9,.-]/g,'').replace(/\./g,'').replace(',','.'))||0);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>'R$ '+Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const short=v=>Math.abs(v)>=1e6?'R$ '+(v/1e6).toLocaleString('pt-BR',{maximumFractionDigits:1})+'M':Math.abs(v)>=1e3?'R$ '+(v/1e3).toLocaleString('pt-BR',{maximumFractionDigits:0})+'K':fmt(v);
const dateBR=v=>v?new Date(v+'T00:00:00').toLocaleDateString('pt-BR'):'—';
const monthName=ym=>{const [y,m]=ym.split('-');return ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'][Number(m)-1]+' de '+y};
const unique=(list,key)=>new Set(list.map(r=>r[key]).filter(Boolean)).size;
const sum=list=>list.reduce((s,r)=>s+r.revenue,0);
function canonicalSeller(value){const raw=String(value||'Não informada').trim(),n=norm(raw);if(n==='leticia')return'Letícia';if(n==='andreia')return'Andréia';if(n==='priscila')return'Priscila';if(n==='loja')return'Loja';if(n==='nao informada'||!n)return'Não informada';return raw}
function canonicalChannel(value){const raw=String(value||'Não informado').trim(),n=norm(raw).replace(/[.]/g,'');if(n.startsWith('pix'))return'Pix';if(n.startsWith('infinity'))return'Infinity';if(n==='pagarme')return'Pagar.me';if(n==='comercial')return'Comercial';if(n==='pagseguro')return'PagSeguro';if(n==='nuvemshop')return'Nuvemshop';return raw||'Não informado'}
function parseState(address){const text=norm(address);for(const [name,uf] of Object.entries(STATE_NAMES))if(text.includes(name))return uf;const match=(' '+String(address||'').toUpperCase()+' ').match(/(?:,|\s|-)(AC|AL|AP|AM|BA|CE|DF|ES|GO|MA|MT|MS|MG|PA|PB|PR|PE|PI|RJ|RN|RS|RO|RR|SC|SP|SE|TO)(?:,|\s|$)/);return match?match[1]:''}
function toRecord(r){const date=String(r['Data de venda']||'').slice(0,10),buyer=String(r['Comprador']||'Não informado').trim(),product=String(r['Produto']||r['Título do anúncio']||'Sem descrição').trim(),channel=canonicalChannel(r['Canal']);return{date,month:date.slice(0,7),buyer,buyerNorm:norm(buyer),channel,title:String(r['Título do anúncio']||r['Produto']||'Sem descrição').trim(),units:money(r['Unidades'])||0,status:String(r['Status']||'').trim(),captured:BASEGERAL_APPROVED.has(norm(r['Status'])),order:String(r['N.º de venda']||'').trim(),revenue:money(r['Fat']),seller:canonicalSeller(r['Vendedora']||((channel==='Nuvemshop')?'Loja':'Não informada')),product,productNorm:norm(product),family:String(r['Perfil de Compra']||'Sem perfil').trim(),state:parseState(r['End']),group:String(r['Grupo']||'').trim().toUpperCase()}}
function toMwRecord(r){const date=String(r['Data de Inclusão (completa)']||'').slice(0,10);if(!date)return null;const merchandise=money(r['Total de Mercadoria']),unit=money(r['Valor Unitário']),buyer=String(r['Cliente (Nome Fantasia)']||r['Cliente (Razão Social)']||'Não informado').trim(),product=String(r['Descrição do Produto']||'Sem descrição').trim(),status=String(r['Situação']||'').trim();return{date,month:date.slice(0,7),buyer,buyerNorm:norm(buyer),channel:'Omie',title:product,units:money(r['Quantidade'])||(unit?merchandise/unit:1),status,captured:ACTIVE.has(norm(status)),order:String(r['Pedido de Venda']||'').trim(),revenue:money(r['Total da Nota Fiscal']),seller:canonicalSeller(r['Vendedor']),product,productNorm:norm(product),family:String(r['Família de Produto']||'Sem família').trim(),state:String(r['Estado']||'').trim().toUpperCase(),group:'MW'}}
function isCaptured(r){return ACTIVE.has(norm(r.status))}
function baseRows(){if(baseCache)return baseCache;const clientQuery=norm(searchClient),productQuery=norm(searchProduct);baseCache=rows.filter(r=>r.captured&&(selectedGroup==='ALL'||r.group===selectedGroup)&&(!selectedChannel||r.channel===selectedChannel)&&(!selectedSeller||r.seller===selectedSeller)&&(!clientQuery||r.buyerNorm.includes(clientQuery))&&(!productQuery||r.productNorm.includes(productQuery)));return baseCache}
function visibleRows(){return baseRows().filter(r=>{if(dateFrom||dateTo){if(dateFrom&&r.date<dateFrom)return false;if(dateTo&&r.date>dateTo)return false;return true}return !selectedMonth||r.month===selectedMonth})}
function rowsForMonth(ym,seller='',dayLimit=31){return baseRows().filter(r=>r.month===ym&&Number(r.date.slice(8,10))<=dayLimit&&(!seller||r.seller===seller))}
function addMonth(ym,delta){const [y,m]=ym.split('-').map(Number),d=new Date(y,m-1+delta,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function growth(current,previous){return previous?((current-previous)/previous)*100:null}
function growthHtml(value){if(value===null||!Number.isFinite(value))return'<span>—</span>';const cls=value>=0?'positive':'negative';return `<span class="${cls}">${value>=0?'▲':'▼'} ${Math.abs(value).toLocaleString('pt-BR',{maximumFractionDigits:1})}%</span>`}
function aggregate(list,key){const map=new Map();list.forEach(r=>{const k=r[key]||'Não informado',z=map.get(k)||{value:0,orders:new Set(),units:0};z.value+=r.revenue;z.units+=r.units;if(r.order)z.orders.add(r.order);map.set(k,z)});return [...map.entries()].sort((a,b)=>b[1].value-a[1].value)}
function goalStorageSeller(group,seller){return group==='MW'?seller:`${group}::${seller}`}
function goalValue(group,seller,month){return Number(goalsMap[`${month}|${goalStorageSeller(group,seller)}`]||0)}
function sellerGroups(seller){return [...new Set(rows.filter(r=>r.captured&&(selectedGroup==='ALL'||r.group===selectedGroup)&&r.seller===seller).map(r=>r.group))]}
function sellerGoal(seller,month){return sellerGroups(seller).reduce((total,group)=>total+goalValue(group,seller,month),0)}
function goalEntries(){const map=new Map();rows.filter(r=>r.captured&&(selectedGroup==='ALL'||r.group===selectedGroup)).forEach(r=>map.set(`${r.group}|${r.seller}`,{group:r.group,seller:r.seller}));return [...map.values()].sort((a,b)=>a.group.localeCompare(b.group)||a.seller.localeCompare(b.seller))}
function totalGoal(month){return goalEntries().reduce((total,item)=>total+goalValue(item.group,item.seller,month),0)}
async function fetchGoals(){const {data,error}=await sb.from('metas_comercial_misterwiz').select('vendedor,mes_ano,meta_captada');if(error){console.warn('Metas não carregadas:',error.message);return}goalsMap={};(data||[]).forEach(r=>goalsMap[`${r.mes_ano}|${r.vendedor}`]=Number(r.meta_captada||0))}
function openGoals(){const months=[...new Set(rows.map(r=>r.month).filter(Boolean))].sort().reverse(),current=selectedMonth||`${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,'0')}`;el('goalsMonth').innerHTML=months.map(m=>`<option value="${m}">${monthName(m)}</option>`).join('');el('goalsMonth').value=months.includes(current)?current:months[0];renderGoalInputs();el('goalsModal').classList.add('show')}
function renderGoalInputs(){const month=el('goalsMonth').value;el('goalsBody').innerHTML=goalEntries().map(item=>`<tr><td>${item.group} · ${esc(item.seller)}</td><td><input class="goal-input" type="number" min="0" step="100" data-group="${item.group}" data-seller="${encodeURIComponent(item.seller)}" value="${goalValue(item.group,item.seller,month)||''}" placeholder="0,00"></td></tr>`).join('')}
async function saveGoals(){const month=el('goalsMonth').value,upserts=[...el('goalsBody').querySelectorAll('.goal-input')].map(input=>({vendedor:goalStorageSeller(input.dataset.group,decodeURIComponent(input.dataset.seller)),mes_ano:month,meta_captada:Number(input.value||0)}));const {error}=await sb.from('metas_comercial_misterwiz').upsert(upserts,{onConflict:'vendedor,mes_ano'});if(error){alert('Erro ao salvar as metas: '+error.message);return}await fetchGoals();el('goalsModal').classList.remove('show');render()}
function render(){baseCache=null;expandedComparisonChannels.clear();if(renderFrame)cancelAnimationFrame(renderFrame);renderFrame=requestAnimationFrame(()=>{renderFrame=0;renderNow()})}
function renderNow(){const data=visibleRows(),revenue=sum(data),orders=unique(data,'order'),clients=unique(data,'buyer'),units=data.reduce((s,r)=>s+r.units,0),month=selectedMonth||comparisonPeriod().month,meta=totalGoal(month),pct=meta?revenue/meta*100:0;el('kpiRevenue').textContent=short(revenue);el('kpiRevenueSub').textContent=`${orders.toLocaleString('pt-BR')} pedido${orders===1?'':'s'} único${orders===1?'':'s'}`;el('kpiClients').textContent=clients.toLocaleString('pt-BR');el('kpiUnits').textContent=units.toLocaleString('pt-BR',{maximumFractionDigits:0});el('kpiOrders').textContent=orders.toLocaleString('pt-BR');el('kpiOrdersSub').textContent=meta?`Meta: ${short(meta)} · ${pct.toLocaleString('pt-BR',{maximumFractionDigits:1})}%`:'Meta: —';el('kpiTicket').textContent=short(orders?revenue/orders:0);el('kpiChannels').textContent=unique(data,'channel').toLocaleString('pt-BR');el('periodChip').textContent=selectedMonth?'Mês: '+monthName(selectedMonth):(dateFrom||dateTo?`Período: ${dateBR(dateFrom)} a ${dateBR(dateTo)}`:'Todos os períodos');renderEvolution();renderSummary();renderDailyWeekly(data);renderRanking(data);renderComparison();renderHistory();scheduleMapRender(data);renderTop(data);renderDetail(data,el('detailTable'),'main')}
function renderEvolution(){const grouped=new Map();baseRows().forEach(r=>{const z=grouped.get(r.month)||{value:0,orders:new Set()};z.value+=r.revenue;if(r.order)z.orders.add(r.order);grouped.set(r.month,z)});const months=[...grouped.keys()].filter(Boolean).sort(),bar=months.map(m=>grouped.get(m).value),ticket=months.map(m=>{const z=grouped.get(m);return z.orders.size?z.value/z.orders.size:0}),blue='#2D70B8',cyan='#009CA6',barColors=months.map(m=>(!dateFrom&&!dateTo&&m===selectedMonth)?cyan:blue),barBorders=months.map(m=>(!dateFrom&&!dateTo&&m===selectedMonth)?'#36E2C9':blue);const datasets=[{type:'bar',label:'Receita Captada',data:bar,backgroundColor:barColors,borderColor:barBorders,borderWidth:months.map(m=>(!dateFrom&&!dateTo&&m===selectedMonth)?2:0),borderRadius:6,maxBarThickness:52,yAxisID:'y'},{type:'line',label:'Ticket Médio',data:ticket,borderColor:'#9AA6B5',backgroundColor:'#9AA6B5',pointRadius:4,tension:.25,yAxisID:'ticket'}];const data={labels:months.map(m=>m.slice(5)+'/'+m.slice(2,4)),datasets};const options={responsive:true,maintainAspectRatio:false,animation:false,interaction:{mode:'index',intersect:false},onClick:(e,items)=>{if(!items.length)return;const clicked=months[items[0].index];selectedMonth=(selectedMonth===clicked&&!dateFrom&&!dateTo)?'':clicked;dateFrom=dateTo='';el('dateFrom').value=el('dateTo').value='';el('monthFilter').value=selectedMonth;render()},onHover:(e,items)=>{e.native.target.style.cursor=items.length?'pointer':'default'},plugins:{legend:{position:'top'},tooltip:{callbacks:{label:c=>`${c.dataset.label}: ${fmt(c.parsed.y)}`}}},scales:{x:{grid:{display:false}},y:{position:'left',ticks:{callback:v=>short(v)}},ticket:{position:'right',grid:{drawOnChartArea:false},ticks:{callback:v=>short(v)}}}};if(monthlyChart){monthlyChart.data=data;monthlyChart.options=options;monthlyChart.update('none')}else monthlyChart=new Chart(el('monthlyChart'),{data,options})}
function comparisonPeriod(){const now=new Date(),month=selectedMonth||`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`,currentMonth=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`,dayLimit=month===currentMonth?now.getDate():31;return{month,previous:addMonth(month,-1),previousYear:addMonth(month,-12),dayLimit}}
function renderSummary(){const p=comparisonPeriod(),cur=rowsForMonth(p.month,'',p.dayLimit),prev=rowsForMonth(p.previous,'',p.dayLimit),curRev=sum(cur),prevRev=sum(prev),curOrders=unique(cur,'order'),prevOrders=unique(prev,'order'),curDays=unique(cur,'date'),prevDays=unique(prev,'date'),curTicket=curOrders?curRev/curOrders:0,prevTicket=prevOrders?prevRev/prevOrders:0;el('summarySub').textContent=`${monthName(p.month)} · comparação com os primeiros ${p.dayLimit} dias de ${monthName(p.previous)}`;el('summaryRevenue').textContent=short(curRev);el('summaryTicket').textContent=short(curTicket);el('summaryOrders').textContent=curOrders.toLocaleString('pt-BR');el('summaryDays').textContent=curDays.toLocaleString('pt-BR');el('summaryRevenueGrowth').innerHTML=growthHtml(growth(curRev,prevRev));el('summaryTicketGrowth').innerHTML=growthHtml(growth(curTicket,prevTicket));el('summaryOrdersGrowth').innerHTML=growthHtml(growth(curOrders,prevOrders));el('summaryDaysGrowth').innerHTML=growthHtml(growth(curDays,prevDays))}
function isoWeek(date){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())),day=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-day+3);const first=new Date(Date.UTC(d.getUTCFullYear(),0,4)),week=1+Math.round(((d-first)/86400000-3+((first.getUTCDay()+6)%7))/7),monday=new Date(date);monday.setDate(monday.getDate()-((date.getDay()+6)%7));const sunday=new Date(monday);sunday.setDate(monday.getDate()+6);return{key:`${d.getUTCFullYear()}-W${String(week).padStart(2,'0')}`,start:monday.toISOString().slice(0,10),end:sunday.toISOString().slice(0,10)}}
function renderDailyWeekly(data){const days=new Map(),weeks=new Map();data.forEach(r=>{days.set(r.date,(days.get(r.date)||0)+r.revenue);const w=isoWeek(new Date(r.date+'T00:00:00')),z=weeks.get(w.key)||{value:0,start:w.start,end:w.end};z.value+=r.revenue;weeks.set(w.key,z)});const dayKeys=[...days.keys()].sort(),weekKeys=[...weeks.keys()].sort(),blue='#2D70B8',cyan='#009CA6',grid='rgba(120,140,160,.18)';const dayData={labels:dayKeys.map(d=>d.slice(8,10)+'/'+d.slice(5,7)),datasets:[{data:dayKeys.map(d=>days.get(d)),borderColor:blue,backgroundColor:blue+'22',fill:true,tension:.35,pointRadius:3}]},dayOpts={responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>fmt(c.parsed.y)}}},onClick:(e,items)=>{if(items.length){dateFrom=dateTo=dayKeys[items[0].index];selectedMonth='';el('monthFilter').value='';el('dateFrom').value=dateFrom;el('dateTo').value=dateTo;render()}},scales:{x:{grid:{display:false}},y:{grid:{color:grid},ticks:{display:false}}}};const weekData={labels:weekKeys.map(k=>'S'+k.slice(-2)+'/'+k.slice(2,4)),datasets:[{data:weekKeys.map(k=>weeks.get(k).value),backgroundColor:blue+'AA',borderColor:cyan,borderRadius:6}]},weekOpts={responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>fmt(c.parsed.y)}}},onClick:(e,items)=>{if(items.length){const w=weeks.get(weekKeys[items[0].index]);dateFrom=w.start;dateTo=w.end;selectedMonth='';el('monthFilter').value='';el('dateFrom').value=dateFrom;el('dateTo').value=dateTo;render()}},scales:{x:{grid:{display:false}},y:{grid:{color:grid},ticks:{display:false}}}};if(dailyChart){dailyChart.data=dayData;dailyChart.options=dayOpts;dailyChart.update('none')}else dailyChart=new Chart(el('dailyChart'),{type:'line',data:dayData,options:dayOpts});if(weeklyChart){weeklyChart.data=weekData;weeklyChart.options=weekOpts;weeklyChart.update('none')}else weeklyChart=new Chart(el('weeklyChart'),{type:'bar',data:weekData,options:weekOpts})}
function renderRanking(data){const total=sum(data),orders=unique(data,'order'),month=selectedMonth||comparisonPeriod().month,rank=aggregate(data,'seller');el('rankingList').innerHTML=rank.length?rank.map(([name,z],i)=>{const ticket=z.orders.size?z.value/z.orders.size:0,meta=sellerGoal(name,month),pct=meta?z.value/meta*100:0;return`<div class="rank-row" onclick="selectSeller(decodeURIComponent('${encodeURIComponent(name)}'))"><span class="rank-pos">${i===0?'🥇':i===1?'🥈':i===2?'🥉':i+1}</span><span>${esc(name)}</span><span>${short(z.value)}</span><span>${meta?short(meta):'—'}</span><span class="${meta?(pct>=100?'positive':'negative'):''}">${meta?pct.toLocaleString('pt-BR',{maximumFractionDigits:1})+'%':'—'}</span><span>${z.orders.size}</span><span>${short(ticket)}</span></div>`}).join(''):'<div class="empty">Sem dados</div>';const meta=totalGoal(month),pct=meta?total/meta*100:0;el('rankingTotal').innerHTML=`<span></span><span>Total</span><span>${short(total)}</span><span>${meta?short(meta):'—'}</span><span class="${meta?(pct>=100?'positive':'negative'):''}">${meta?pct.toLocaleString('pt-BR',{maximumFractionDigits:1})+'%':'—'}</span><span>${orders}</span><span>${short(orders?total/orders:0)}</span>`}
function selectSeller(name){selectedSeller=selectedSeller===name?'':name;el('sellerFilter').value=selectedSeller;render()}
function channelMetrics(channel,month,day){const rr=rowsForMonth(month,'',day).filter(r=>r.channel===channel),rev=sum(rr),orders=unique(rr,'order');return{rows:rr,rev,orders,ticket:orders?rev/orders:0}}
function comparisonChannelProductRows(channel,product,month,dayLimit){return rowsForMonth(month,'',dayLimit).filter(r=>r.channel===channel&&r.product===product)}
function renderComparison(){const p=comparisonPeriod(),allCurrent=rowsForMonth(p.month,'',p.dayLimit),total=sum(allCurrent)||1,channels=[...new Set(baseRows().map(r=>r.channel).filter(Boolean))].map(channel=>({channel,rev:channelMetrics(channel,p.month,p.dayLimit).rev})).sort((a,b)=>b.rev-a.rev).map(x=>x.channel);let body='';channels.forEach(channel=>{const c=channelMetrics(channel,p.month,p.dayLimit),ma=channelMetrics(channel,p.previous,p.dayLimit),aa=channelMetrics(channel,p.previousYear,p.dayLimit),expanded=expandedComparisonChannels.has(channel);if(!c.rev&&!ma.rev&&!aa.rev)return;body+=`<tr><td><button class="toggle" onclick="toggleComparisonChannel(decodeURIComponent('${encodeURIComponent(channel)}'))">${expanded?'−':'+'}</button> <button class="seller-link" onclick="openChannel(decodeURIComponent('${encodeURIComponent(channel)}'))">${esc(channel)}</button></td><td>${fmt(c.rev)}</td><td>${(c.rev/total*100).toLocaleString('pt-BR',{maximumFractionDigits:1})}%</td><td>${fmt(ma.rev)}</td><td class="${c.rev-ma.rev>=0?'positive':'negative'}">${fmt(c.rev-ma.rev)}</td><td>${growthHtml(growth(c.rev,ma.rev))}</td><td>${fmt(aa.rev)}</td><td class="${c.rev-aa.rev>=0?'positive':'negative'}">${fmt(c.rev-aa.rev)}</td><td>${growthHtml(growth(c.rev,aa.rev))}</td><td>${fmt(c.ticket)}</td></tr>`;if(expanded){const products=[...new Set([...c.rows,...ma.rows,...aa.rows].map(r=>r.product).filter(Boolean))].map(product=>({product,rev:sum(c.rows.filter(r=>r.product===product))})).sort((a,b)=>b.rev-a.rev);products.forEach(({product})=>{const cr=c.rows.filter(r=>r.product===product),mr=ma.rows.filter(r=>r.product===product),ar=comparisonChannelProductRows(channel,product,p.previousYear,p.dayLimit),cv=sum(cr),mv=sum(mr),av=sum(ar),orders=unique(cr,'order'),ticket=orders?cv/orders:0;body+=`<tr class="comparison-product"><td><button class="product-link" onclick="openProduct(decodeURIComponent('${encodeURIComponent(product)}'))">↳ ${esc(product)}</button></td><td>${fmt(cv)}</td><td>${(cv/total*100).toLocaleString('pt-BR',{maximumFractionDigits:1})}%</td><td>${fmt(mv)}</td><td class="${cv-mv>=0?'positive':'negative'}">${fmt(cv-mv)}</td><td>${growthHtml(growth(cv,mv))}</td><td>${fmt(av)}</td><td class="${cv-av>=0?'positive':'negative'}">${fmt(cv-av)}</td><td>${growthHtml(growth(cv,av))}</td><td>${fmt(ticket)}</td></tr>`})}});const cur=sum(allCurrent),ma=sum(rowsForMonth(p.previous,'',p.dayLimit)),aa=sum(rowsForMonth(p.previousYear,'',p.dayLimit)),orders=unique(allCurrent,'order');el('comparisonBody').innerHTML=(body||'<tr><td colspan="10" class="empty">Sem dados</td></tr>')+(body?`<tr><td><b>Total</b></td><td><b>${fmt(cur)}</b></td><td>100%</td><td>${fmt(ma)}</td><td class="${cur-ma>=0?'positive':'negative'}">${fmt(cur-ma)}</td><td>${growthHtml(growth(cur,ma))}</td><td>${fmt(aa)}</td><td class="${cur-aa>=0?'positive':'negative'}">${fmt(cur-aa)}</td><td>${growthHtml(growth(cur,aa))}</td><td>${fmt(orders?cur/orders:0)}</td></tr>`:'')}
function toggleComparisonChannel(channel){if(expandedComparisonChannels.has(channel))expandedComparisonChannels.delete(channel);else expandedComparisonChannels.add(channel);renderComparison()}
function openChannel(channel){openDetails(baseRows().filter(r=>r.channel===channel),`Canal: ${channel}`)}
function renderHistory(){const base=baseRows(),months=[...new Set(base.map(r=>r.month).filter(Boolean))].sort(),sellerMap=new Map();base.forEach(r=>{if(!sellerMap.has(r.seller))sellerMap.set(r.seller,[]);sellerMap.get(r.seller).push(r)});historyRowStore.clear();const head='<th>Vendedor</th>'+months.map(m=>`<th>${m.slice(5)}/${m.slice(2,4)}</th>`).join('')+'<th>Total</th>',body=[...sellerMap.entries()].sort((a,b)=>a[0].localeCompare(b[0],'pt-BR')).map(([seller,rr],i)=>{const id='hist-'+i,totals=new Map();rr.forEach(r=>totals.set(r.month,(totals.get(r.month)||0)+r.revenue));historyRowStore.set(id,{rows:rr,months,rendered:0,clients:null});return`<tr id="row-${id}"><td><button class="toggle" onclick="toggleHistory('${id}',this)">+</button> ${esc(seller)}</td>${months.map(m=>`<td>${short(totals.get(m)||0)}</td>`).join('')}<td><b>${short(sum(rr))}</b></td></tr>`}).join('');el('historyWrap').innerHTML=`<table class="history-table"><thead><tr>${head}</tr></thead><tbody>${body||'<tr><td class="empty">Sem dados</td></tr>'}</tbody></table>`}
function historyClients(state){if(state.clients)return state.clients;const map=new Map();state.rows.forEach(r=>{let z=map.get(r.buyer);if(!z){z={name:r.buyer,total:0,months:new Map()};map.set(r.buyer,z)}z.total+=r.revenue;z.months.set(r.month,(z.months.get(r.month)||0)+r.revenue)});state.clients=[...map.values()].sort((a,b)=>b.total-a.total);return state.clients}
function appendHistoryClients(id){const state=historyRowStore.get(id);if(!state)return;const clients=historyClients(state),batch=clients.slice(state.rendered,state.rendered+100);document.querySelector(`.history-more.group-${id}`)?.remove();const anchor=[...document.querySelectorAll('.group-'+id)].pop()||document.getElementById('row-'+id);state.rendered+=batch.length;const rows=batch.map(z=>`<tr class="history-client open group-${id}"><td><button class="client-link" onclick="openClient(decodeURIComponent('${encodeURIComponent(z.name)}'))">↳ ${esc(z.name)}</button></td>${state.months.map(m=>`<td>${short(z.months.get(m)||0)}</td>`).join('')}<td><b>${short(z.total)}</b></td></tr>`).join(''),more=state.rendered<clients.length?`<tr class="history-client history-more open group-${id}"><td colspan="${state.months.length+2}"><button class="load-more" onclick="appendHistoryClients('${id}')">Mostrar mais clientes (${clients.length-state.rendered})</button></td></tr>`:'';anchor.insertAdjacentHTML('afterend',rows+more)}
function toggleHistory(id,button){let rr=document.querySelectorAll('.group-'+id);if(!rr.length){appendHistoryClients(id);rr=document.querySelectorAll('.group-'+id);button.textContent='−';return}const open=!rr[0].classList.contains('open');rr.forEach(r=>r.classList.toggle('open',open));button.textContent=open?'−':'+'}
function scheduleMapRender(data){if(mapTask){if(window.cancelIdleCallback)cancelIdleCallback(mapTask);else clearTimeout(mapTask)}const run=()=>{mapTask=0;renderMap(data)};mapTask=window.requestIdleCallback?requestIdleCallback(run,{timeout:450}):setTimeout(run,80)}
function renderMap(data){if(!window.L)return;if(!leafletMap){leafletMap=L.map('revenueMap',{zoomControl:true,scrollWheelZoom:true}).setView([-14.2,-51.9],4);L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:18,subdomains:'abcd',attribution:'© OpenStreetMap © CARTO'}).addTo(leafletMap);leafletLayer=L.layerGroup().addTo(leafletMap)}leafletLayer.clearLayers();const map={};data.forEach(r=>{if(UF_COORDS[r.state])map[r.state]=(map[r.state]||0)+r.revenue});const max=Math.max(...Object.values(map),1);Object.entries(map).forEach(([uf,val])=>{const [lat,lng]=UF_COORDS[uf];L.circleMarker([lat,lng],{radius:6+(val/max)*22,fillColor:'#2D70B8',color:'#36E2C9',weight:1.5,fillOpacity:.65,className:'pulse-marker'}).bindTooltip(`${uf}: ${fmt(val)}`).bindPopup(`<b>${uf}</b><br>Receita captada: ${fmt(val)}`).addTo(leafletLayer)});setTimeout(()=>leafletMap.invalidateSize(),60)}
function renderTop(data){const configs=[['buyer',el('clientTable'),false],['family',el('familyTable'),false],['product',el('productTable'),true]];configs.forEach(([key,body,isProduct])=>{const list=aggregate(data,key).slice(0,10);body.innerHTML=list.length?list.map(([name,z])=>`<tr><td>${key==='buyer'?`<button class="client-link" onclick="openClient(decodeURIComponent('${encodeURIComponent(name)}'))">${esc(name)}</button>`:key==='product'?`<button class="product-link" onclick="openProduct(decodeURIComponent('${encodeURIComponent(name)}'))">${esc(name)}</button>`:esc(name)}</td><td>${short(z.value)}</td><td>${isProduct?z.units.toLocaleString('pt-BR',{maximumFractionDigits:0}):z.orders.size}</td></tr>`).join(''):'<tr><td colspan="3" class="empty">Sem dados</td></tr>'})}
function openProduct(product){const history=baseRows().filter(r=>r.product===product),months=[...new Set(history.map(r=>r.month).filter(Boolean))].sort(),revenue=sum(history),orders=unique(history,'order'),clients=unique(history,'buyer');el('productModalTitle').textContent=product;el('productRevenue').textContent=fmt(revenue);el('productOrders').textContent=orders.toLocaleString('pt-BR');el('productClients').textContent=clients.toLocaleString('pt-BR');el('productTicket').textContent=fmt(orders?revenue/orders:0);el('productModal').classList.add('show');setTimeout(()=>{const chartData={labels:months.map(m=>m.slice(5)+'/'+m.slice(2,4)),datasets:[{type:'bar',label:'Receita Captada',data:months.map(m=>sum(history.filter(r=>r.month===m))),backgroundColor:'#2D70B8',borderRadius:6,yAxisID:'y'},{type:'line',label:'Ticket Médio',data:months.map(m=>{const rr=history.filter(r=>r.month===m),o=unique(rr,'order');return o?sum(rr)/o:0}),borderColor:'#9AA6B5',backgroundColor:'#9AA6B5',pointRadius:4,tension:.25,yAxisID:'ticket'}]},options={responsive:true,maintainAspectRatio:false,animation:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'top'},tooltip:{callbacks:{label:c=>`${c.dataset.label}: ${fmt(c.parsed.y)}`}}},scales:{y:{position:'left',ticks:{callback:v=>short(v)}},ticket:{position:'right',grid:{drawOnChartArea:false},ticks:{callback:v=>short(v)}}}};if(productHistoryChart){productHistoryChart.data=chartData;productHistoryChart.options=options;productHistoryChart.update('none')}else productHistoryChart=new Chart(el('productHistoryChart'),{data:chartData,options})},0);const top=aggregate(history,'buyer').slice(0,3);el('productTopClients').innerHTML=top.length?top.map(([name,z],i)=>`<button class="top-client-card" onclick="openHistoricalClient(decodeURIComponent('${encodeURIComponent(name)}'))"><b>${i+1}º · ${esc(name)}</b><span>${fmt(z.value)} · ${z.orders.size} pedido${z.orders.size===1?'':'s'}</span></button>`).join(''):'<div class="empty">Sem clientes</div>'}
function openHistoricalClient(client){el('productModal').classList.remove('show');openClient(client)}
function renderDetail(list,body,prefix){for(const key of [...detailRowStore.keys()])if(key.startsWith(prefix+'-'))detailRowStore.delete(key);const groups=new Map();list.forEach(r=>{if(!groups.has(r.buyer))groups.set(r.buyer,[]);groups.get(r.buyer).push(r)});body.innerHTML=groups.size?[...groups.entries()].sort((a,b)=>sum(b[1])-sum(a[1])).map(([client,rr],i)=>{const id=`${prefix}-${i}`,total=sum(rr),units=rr.reduce((s,r)=>s+r.units,0),orders=unique(rr,'order');detailRowStore.set(id,rr);return`<tr class="client-row" id="row-${id}"><td><button class="toggle" onclick="toggleGroup('${id}',this)">+</button></td><td><button class="client-link" onclick="openClient(decodeURIComponent('${encodeURIComponent(client)}'))">${esc(client)}</button></td><td>${[...new Set(rr.map(r=>r.group))].join(', ')}</td><td>${esc([...new Set(rr.map(r=>r.seller))].join(', '))}</td><td>${esc([...new Set(rr.map(r=>r.channel))].join(', '))}</td><td>${orders}</td><td>—</td><td>—</td><td>${units.toLocaleString('pt-BR',{maximumFractionDigits:2})}</td><td>${fmt(total)}</td></tr>`}).join(''):'<tr><td colspan="10" class="empty">Nenhum registro encontrado.</td></tr>'}
function toggleGroup(id,button){let rr=document.querySelectorAll('.group-'+id);if(!rr.length){const rowsForClient=detailRowStore.get(id)||[],html=rowsForClient.map(r=>`<tr class="product-row open group-${id}"><td></td><td>${esc(r.product)}</td><td>${r.group}</td><td>${esc(r.seller)}</td><td>${esc(r.channel)}</td><td>${esc(r.order||'—')}</td><td>${esc(r.status)}</td><td>${dateBR(r.date)}</td><td>${r.units.toLocaleString('pt-BR',{maximumFractionDigits:2})}</td><td>${fmt(r.revenue)}</td></tr>`).join('');document.getElementById('row-'+id)?.insertAdjacentHTML('afterend',html);button.textContent='−';return}const open=!rr[0].classList.contains('open');rr.forEach(r=>r.classList.toggle('open',open));button.textContent=open?'−':'+'}
function openClient(client){openDetails(baseRows().filter(r=>r.buyer===client),`Cliente: ${client}`)}
function openDetails(list,title){el('modalTitle').textContent=title;el('modalValue').textContent=fmt(sum(list));el('modalOrders').textContent=unique(list,'order');el('modalClients').textContent=unique(list,'buyer');el('modalUnits').textContent=list.reduce((s,r)=>s+r.units,0).toLocaleString('pt-BR',{maximumFractionDigits:0});renderDetail(list,el('modalBody'),'modal');el('statusModal').classList.add('show')}
function queueSearch(kind,value){clearTimeout(searchTimer);searchTimer=setTimeout(()=>{if(kind==='client')searchClient=value;else searchProduct=value;render()},260)}
function populate(){const months=[...new Set(rows.map(r=>r.month).filter(Boolean))].sort().reverse(),current=`${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,'0')}`;el('monthFilter').innerHTML='<option value="">Todos os meses</option>'+months.map(m=>`<option value="${m}">${monthName(m)}</option>`).join('');selectedMonth=months.includes(current)?current:(months[0]||'');el('monthFilter').value=selectedMonth;const channels=[...new Set(rows.map(r=>r.channel).filter(Boolean))].sort(),sellers=[...new Set(rows.map(r=>r.seller).filter(Boolean))].sort();el('channelFilter').innerHTML='<option value="">Todos</option>'+channels.map(v=>`<option>${esc(v)}</option>`).join('');el('sellerFilter').innerHTML='<option value="">Todos</option>'+sellers.map(v=>`<option>${esc(v)}</option>`).join('')}
function bind(){document.querySelectorAll('[data-group]').forEach(b=>b.addEventListener('click',()=>{selectedGroup=b.dataset.group;selectedSeller=selectedChannel='';expandedComparisonChannels.clear();el('sellerFilter').value=el('channelFilter').value='';document.querySelectorAll('[data-group]').forEach(x=>x.classList.toggle('active',x===b));el('groupBadge').textContent=selectedGroup==='ALL'?'Grupo UUIZZ':selectedGroup;render()}));el('monthFilter').addEventListener('change',e=>{selectedMonth=e.target.value;dateFrom=dateTo='';el('dateFrom').value=el('dateTo').value='';render()});el('dateFrom').addEventListener('change',e=>{dateFrom=e.target.value;selectedMonth='';el('monthFilter').value='';render()});el('dateTo').addEventListener('change',e=>{dateTo=e.target.value;selectedMonth='';el('monthFilter').value='';render()});el('channelFilter').addEventListener('change',e=>{selectedChannel=e.target.value;render()});el('sellerFilter').addEventListener('change',e=>{selectedSeller=e.target.value;render()});el('searchClient').addEventListener('input',e=>queueSearch('client',e.target.value));el('searchProduct').addEventListener('input',e=>queueSearch('product',e.target.value));el('clearDates').addEventListener('click',()=>{dateFrom=dateTo='';el('dateFrom').value=el('dateTo').value='';render()});el('capturedCard').addEventListener('click',()=>openDetails(visibleRows(),'Receita Captada'));el('modalClose').addEventListener('click',()=>el('statusModal').classList.remove('show'));el('statusModal').addEventListener('click',e=>{if(e.target===el('statusModal'))el('statusModal').classList.remove('show')});el('openGoals').addEventListener('click',openGoals);el('goalsMonth').addEventListener('change',renderGoalInputs);el('goalsSave').addEventListener('click',saveGoals);el('goalsClose').addEventListener('click',()=>el('goalsModal').classList.remove('show'));el('goalsCancel').addEventListener('click',()=>el('goalsModal').classList.remove('show'));el('goalsModal').addEventListener('click',e=>{if(e.target===el('goalsModal'))el('goalsModal').classList.remove('show')});el('productModalClose').addEventListener('click',()=>el('productModal').classList.remove('show'));el('productModal').addEventListener('click',e=>{if(e.target===el('productModal'))el('productModal').classList.remove('show')})}
async function logout(){await sb.auth.signOut();location.href='index.html'}
async function init(){const {data:{session}}=await sb.auth.getSession();if(!session){location.href='index.html';return}currentUser=session.user;const email=(currentUser.email||'').toLowerCase();if(RESTRICTED.includes(email)){location.replace('painel.html');return}if(!(email.endsWith('@gpsbi.com.br')||email==='daniela@empoderamentoadolescente.com.br')){location.href='index.html';return}const eaCw=(window.UUIZZ_GROUP_COMMERCIAL_DATA||[]).map(toRecord).filter(r=>r.group==='EA'||r.group==='CW'),mw=(window.MISTER_WIZ_COMMERCIAL_DATA||[]).map(toMwRecord).filter(Boolean);rows=[...eaCw,...mw];renderAppNav({activePage:'painelgrupo.html',userLabel:email.split('@')[0]||'Usuário',userRole:'owner',onLogout:logout,sb,currentUser});populate();const requested=(new URLSearchParams(location.search).get('grupo')||'').toUpperCase();if(requested==='EA'||requested==='CW')selectedGroup=requested;await fetchGoals();bind();document.querySelectorAll('[data-group]').forEach(b=>b.classList.toggle('active',b.dataset.group===selectedGroup));el('groupBadge').textContent=selectedGroup==='ALL'?'Grupo UUIZZ':selectedGroup;el('loadingScreen').style.display='none';el('mainContent').style.display='block';render()}
init();
