const SUPABASE_URL='https://okrvklvvulmjdarlwdbl.supabase.co';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJva3J2a2x2dnVsbWpkYXJsd2RibCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzgzOTU4MTkxLCJleHAiOjIwOTk1MzQxOTF9.X8lXu_ZHB1v_tSvQso4RVEWt32NaI7gPZrTlQsB6dog';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const RESTRICTED=['miria@misterwiz.com.br','custodio@sforza.com.br'];
const ACTIVE=new Set(['completo','aprovado','paga','faturado','aguardando pagto','pendente','ag. pagamento','boleto impresso','pending','iniciada','aguardando faturamento','atrasado','faturamento atrasado']);
const UF_COORDS={AC:[-9.97,-67.81],AL:[-9.62,-36.82],AP:[.03,-51.05],AM:[-3.10,-60.02],BA:[-12.97,-38.50],CE:[-3.73,-38.52],DF:[-15.79,-47.88],ES:[-20.31,-40.31],GO:[-16.68,-49.25],MA:[-2.53,-44.30],MT:[-15.60,-56.10],MS:[-20.45,-54.62],MG:[-19.92,-43.94],PA:[-1.45,-48.49],PB:[-7.12,-34.86],PR:[-25.43,-49.27],PE:[-8.05,-34.90],PI:[-5.09,-42.80],RJ:[-22.91,-43.17],RN:[-5.79,-35.21],RS:[-30.03,-51.23],RO:[-8.76,-63.90],RR:[2.82,-60.67],SC:[-27.59,-48.55],SP:[-23.55,-46.63],SE:[-10.91,-37.07],TO:[-10.18,-48.33]};
const STATE_NAMES={acre:'AC',alagoas:'AL',amapa:'AP',amazonas:'AM',bahia:'BA',ceara:'CE','distrito federal':'DF','espirito santo':'ES',goias:'GO',maranhao:'MA','mato grosso':'MT','mato grosso do sul':'MS','minas gerais':'MG',para:'PA',paraiba:'PB',parana:'PR',pernambuco:'PE',piaui:'PI','rio de janeiro':'RJ','rio grande do norte':'RN','rio grande do sul':'RS',rondonia:'RO',roraima:'RR','santa catarina':'SC','sao paulo':'SP',sergipe:'SE',tocantins:'TO'};
let rows=[],selectedGroup='ALL',selectedMonth='',dateFrom='',dateTo='',selectedChannel='',selectedSeller='',searchClient='',searchProduct='';
let monthlyChart,dailyChart,weeklyChart,leafletMap,leafletLayer,currentUser;
const el=id=>document.getElementById(id);
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const money=v=>typeof v==='number'?v:(parseFloat(String(v??'0').replace(/[^0-9,.-]/g,'').replace(/\./g,'').replace(',','.'))||0);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>'R$ '+Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const short=v=>Math.abs(v)>=1e6?'R$ '+(v/1e6).toLocaleString('pt-BR',{maximumFractionDigits:1})+'M':Math.abs(v)>=1e3?'R$ '+(v/1e3).toLocaleString('pt-BR',{maximumFractionDigits:0})+'K':fmt(v);
const dateBR=v=>v?new Date(v+'T00:00:00').toLocaleDateString('pt-BR'):'—';
const monthName=ym=>{const [y,m]=ym.split('-');return ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'][Number(m)-1]+' de '+y};
const unique=(list,key)=>new Set(list.map(r=>r[key]).filter(Boolean)).size;
const sum=list=>list.reduce((s,r)=>s+r.revenue,0);
function parseState(address){const text=norm(address);for(const [name,uf] of Object.entries(STATE_NAMES))if(text.includes(name))return uf;const match=(' '+String(address||'').toUpperCase()+' ').match(/(?:,|\s|-)(AC|AL|AP|AM|BA|CE|DF|ES|GO|MA|MT|MS|MG|PA|PB|PR|PE|PI|RJ|RN|RS|RO|RR|SC|SP|SE|TO)(?:,|\s|$)/);return match?match[1]:''}
function toRecord(r){const date=String(r['Data de venda']||'').slice(0,10);return{date,month:date.slice(0,7),buyer:String(r['Comprador']||'Não informado').trim(),channel:String(r['Canal']||'Não informado').trim(),title:String(r['Título do anúncio']||r['Produto']||'Sem descrição').trim(),units:money(r['Unidades'])||0,status:String(r['Status']||'').trim(),order:String(r['N.º de venda']||'').trim(),revenue:money(r['Fat']),seller:String(r['Vendedora']||((r['Canal']==='Nuvemshop')?'Loja':'Não informada')).trim(),product:String(r['Produto']||r['Título do anúncio']||'Sem descrição').trim(),family:String(r['Perfil de Compra']||'Sem perfil').trim(),state:parseState(r['End']),group:String(r['Grupo']||'').trim().toUpperCase()}}
function toMwRecord(r){const date=String(r['Data de Inclusão (completa)']||'').slice(0,10);if(!date)return null;const merchandise=money(r['Total de Mercadoria']),unit=money(r['Valor Unitário']);return{date,month:date.slice(0,7),buyer:String(r['Cliente (Nome Fantasia)']||r['Cliente (Razão Social)']||'Não informado').trim(),channel:'Omie',title:String(r['Descrição do Produto']||'Sem descrição').trim(),units:money(r['Quantidade'])||(unit?merchandise/unit:1),status:String(r['Situação']||'').trim(),order:String(r['Pedido de Venda']||'').trim(),revenue:money(r['Total da Nota Fiscal']),seller:String(r['Vendedor']||'Não informada').trim(),product:String(r['Descrição do Produto']||'Sem descrição').trim(),family:String(r['Família de Produto']||'Sem família').trim(),state:String(r['Estado']||'').trim().toUpperCase(),group:'MW'}}
function isCaptured(r){return ACTIVE.has(norm(r.status))}
function baseRows(){return rows.filter(r=>isCaptured(r)&&(selectedGroup==='ALL'||r.group===selectedGroup)&&(!selectedChannel||r.channel===selectedChannel)&&(!selectedSeller||r.seller===selectedSeller)&&(!searchClient||norm(r.buyer).includes(norm(searchClient)))&&(!searchProduct||norm(r.product).includes(norm(searchProduct))))}
function visibleRows(){return baseRows().filter(r=>{if(dateFrom||dateTo){if(dateFrom&&r.date<dateFrom)return false;if(dateTo&&r.date>dateTo)return false;return true}return !selectedMonth||r.month===selectedMonth})}
function rowsForMonth(ym,seller='',dayLimit=31){return rows.filter(r=>isCaptured(r)&&(selectedGroup==='ALL'||r.group===selectedGroup)&&r.month===ym&&Number(r.date.slice(8,10))<=dayLimit&&(!selectedChannel||r.channel===selectedChannel)&&(!seller||r.seller===seller)&&(!searchClient||norm(r.buyer).includes(norm(searchClient)))&&(!searchProduct||norm(r.product).includes(norm(searchProduct))))}
function addMonth(ym,delta){const [y,m]=ym.split('-').map(Number),d=new Date(y,m-1+delta,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function growth(current,previous){return previous?((current-previous)/previous)*100:null}
function growthHtml(value){if(value===null||!Number.isFinite(value))return'<span>—</span>';const cls=value>=0?'positive':'negative';return `<span class="${cls}">${value>=0?'▲':'▼'} ${Math.abs(value).toLocaleString('pt-BR',{maximumFractionDigits:1})}%</span>`}
function aggregate(list,key){const map=new Map();list.forEach(r=>{const k=r[key]||'Não informado',z=map.get(k)||{value:0,orders:new Set(),units:0};z.value+=r.revenue;z.units+=r.units;if(r.order)z.orders.add(r.order);map.set(k,z)});return [...map.entries()].sort((a,b)=>b[1].value-a[1].value)}
function render(){const data=visibleRows(),revenue=sum(data),orders=unique(data,'order'),clients=unique(data,'buyer'),units=data.reduce((s,r)=>s+r.units,0);el('kpiRevenue').textContent=short(revenue);el('kpiRevenueSub').textContent=`${orders.toLocaleString('pt-BR')} pedido${orders===1?'':'s'} único${orders===1?'':'s'}`;el('kpiClients').textContent=clients.toLocaleString('pt-BR');el('kpiUnits').textContent=units.toLocaleString('pt-BR',{maximumFractionDigits:0});el('kpiOrders').textContent=orders.toLocaleString('pt-BR');el('kpiTicket').textContent=short(orders?revenue/orders:0);el('kpiChannels').textContent=unique(data,'channel').toLocaleString('pt-BR');el('periodChip').textContent=selectedMonth?'Mês: '+monthName(selectedMonth):(dateFrom||dateTo?`Período: ${dateBR(dateFrom)} a ${dateBR(dateTo)}`:'Todos os períodos');renderEvolution();renderSummary();renderDailyWeekly(data);renderRanking(data);renderComparison();renderHistory();renderMap(data);renderTop(data);renderDetail(data,el('detailTable'),'main')}
function renderEvolution(){const base=baseRows(),months=[...new Set(base.map(r=>r.month).filter(Boolean))].sort(),groups=selectedGroup==='ALL'?['EA','CW','MW']:[selectedGroup],colors={EA:'#2D70B8',CW:'#E2A21B',MW:'#16A085'};const datasets=groups.map(g=>({type:'bar',label:g,data:months.map(m=>sum(base.filter(r=>r.group===g&&r.month===m))),backgroundColor:colors[g],borderRadius:5,maxBarThickness:40,stack:'revenue',yAxisID:'y'}));datasets.push({type:'line',label:'Ticket Médio',data:months.map(m=>{const rr=base.filter(r=>r.month===m),o=unique(rr,'order');return o?sum(rr)/o:0}),borderColor:'#9AA6B5',backgroundColor:'#9AA6B5',pointRadius:4,tension:.25,yAxisID:'ticket'});const data={labels:months.map(m=>m.slice(5)+'/'+m.slice(2,4)),datasets};const options={responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},onClick:(e,items)=>{if(items.length){selectedMonth=months[items[0].index];dateFrom=dateTo='';el('monthFilter').value=selectedMonth;render()}},plugins:{legend:{position:'top'},tooltip:{callbacks:{label:c=>`${c.dataset.label}: ${fmt(c.parsed.y)}`}}},scales:{x:{stacked:true,grid:{display:false}},y:{stacked:true,position:'left',ticks:{callback:v=>short(v)}},ticket:{position:'right',grid:{drawOnChartArea:false},ticks:{callback:v=>short(v)}}}};if(monthlyChart){monthlyChart.data=data;monthlyChart.options=options;monthlyChart.update()}else monthlyChart=new Chart(el('monthlyChart'),{data,options})}
function comparisonPeriod(){const now=new Date(),month=selectedMonth||`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`,currentMonth=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`,dayLimit=month===currentMonth?now.getDate():31;return{month,previous:addMonth(month,-1),previousYear:addMonth(month,-12),dayLimit}}
function renderSummary(){const p=comparisonPeriod(),cur=rowsForMonth(p.month,'',p.dayLimit),prev=rowsForMonth(p.previous,'',p.dayLimit),curRev=sum(cur),prevRev=sum(prev),curOrders=unique(cur,'order'),prevOrders=unique(prev,'order'),curDays=unique(cur,'date'),prevDays=unique(prev,'date'),curTicket=curOrders?curRev/curOrders:0,prevTicket=prevOrders?prevRev/prevOrders:0;el('summarySub').textContent=`${monthName(p.month)} · comparação com os primeiros ${p.dayLimit} dias de ${monthName(p.previous)}`;el('summaryRevenue').textContent=short(curRev);el('summaryTicket').textContent=short(curTicket);el('summaryOrders').textContent=curOrders.toLocaleString('pt-BR');el('summaryDays').textContent=curDays.toLocaleString('pt-BR');el('summaryRevenueGrowth').innerHTML=growthHtml(growth(curRev,prevRev));el('summaryTicketGrowth').innerHTML=growthHtml(growth(curTicket,prevTicket));el('summaryOrdersGrowth').innerHTML=growthHtml(growth(curOrders,prevOrders));el('summaryDaysGrowth').innerHTML=growthHtml(growth(curDays,prevDays))}
function isoWeek(date){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())),day=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-day+3);const first=new Date(Date.UTC(d.getUTCFullYear(),0,4)),week=1+Math.round(((d-first)/86400000-3+((first.getUTCDay()+6)%7))/7),monday=new Date(date);monday.setDate(monday.getDate()-((date.getDay()+6)%7));const sunday=new Date(monday);sunday.setDate(monday.getDate()+6);return{key:`${d.getUTCFullYear()}-W${String(week).padStart(2,'0')}`,start:monday.toISOString().slice(0,10),end:sunday.toISOString().slice(0,10)}}
function renderDailyWeekly(data){const days=new Map(),weeks=new Map();data.forEach(r=>{days.set(r.date,(days.get(r.date)||0)+r.revenue);const w=isoWeek(new Date(r.date+'T00:00:00')),z=weeks.get(w.key)||{value:0,start:w.start,end:w.end};z.value+=r.revenue;weeks.set(w.key,z)});const dayKeys=[...days.keys()].sort(),weekKeys=[...weeks.keys()].sort(),blue='#2D70B8',cyan='#009CA6',grid='rgba(120,140,160,.18)';const dayData={labels:dayKeys.map(d=>d.slice(8,10)+'/'+d.slice(5,7)),datasets:[{data:dayKeys.map(d=>days.get(d)),borderColor:blue,backgroundColor:blue+'22',fill:true,tension:.35,pointRadius:3}]},dayOpts={responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>fmt(c.parsed.y)}}},onClick:(e,items)=>{if(items.length){dateFrom=dateTo=dayKeys[items[0].index];selectedMonth='';el('monthFilter').value='';el('dateFrom').value=dateFrom;el('dateTo').value=dateTo;render()}},scales:{x:{grid:{display:false}},y:{grid:{color:grid},ticks:{display:false}}}};const weekData={labels:weekKeys.map(k=>'S'+k.slice(-2)+'/'+k.slice(2,4)),datasets:[{data:weekKeys.map(k=>weeks.get(k).value),backgroundColor:blue+'AA',borderColor:cyan,borderRadius:6}]},weekOpts={responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>fmt(c.parsed.y)}}},onClick:(e,items)=>{if(items.length){const w=weeks.get(weekKeys[items[0].index]);dateFrom=w.start;dateTo=w.end;selectedMonth='';el('monthFilter').value='';el('dateFrom').value=dateFrom;el('dateTo').value=dateTo;render()}},scales:{x:{grid:{display:false}},y:{grid:{color:grid},ticks:{display:false}}}};if(dailyChart){dailyChart.data=dayData;dailyChart.options=dayOpts;dailyChart.update()}else dailyChart=new Chart(el('dailyChart'),{type:'line',data:dayData,options:dayOpts});if(weeklyChart){weeklyChart.data=weekData;weeklyChart.options=weekOpts;weeklyChart.update()}else weeklyChart=new Chart(el('weeklyChart'),{type:'bar',data:weekData,options:weekOpts})}
function renderRanking(data){const total=sum(data)||1,rank=aggregate(data,'seller');el('rankingList').innerHTML=rank.length?rank.map(([name,z],i)=>{const ticket=z.orders.size?z.value/z.orders.size:0,pct=z.value/total*100;return`<div class="rank-row" onclick="selectSeller(decodeURIComponent('${encodeURIComponent(name)}'))"><span class="rank-pos">${i===0?'🥇':i===1?'🥈':i===2?'🥉':i+1}</span><span>${esc(name)}</span><span>${short(z.value)}</span><span>${z.orders.size}</span><span>${short(ticket)}</span><span>${pct.toLocaleString('pt-BR',{maximumFractionDigits:1})}%</span></div>`}).join(''):'<div class="empty">Sem dados</div>'}
function selectSeller(name){selectedSeller=selectedSeller===name?'':name;el('sellerFilter').value=selectedSeller;render()}
function sellerMetrics(seller,month,day){const rr=rowsForMonth(month,seller,day),rev=sum(rr),orders=unique(rr,'order');return{rows:rr,rev,orders,ticket:orders?rev/orders:0}}
function renderComparison(){const p=comparisonPeriod(),sellers=[...new Set(baseRows().map(r=>r.seller).filter(Boolean))],allCurrent=rowsForMonth(p.month,'',p.dayLimit),total=sum(allCurrent)||1;const body=sellers.map(s=>{const c=sellerMetrics(s,p.month,p.dayLimit),ma=sellerMetrics(s,p.previous,p.dayLimit),aa=sellerMetrics(s,p.previousYear,p.dayLimit);if(!c.rev&&!ma.rev&&!aa.rev)return'';return`<tr><td><button class="seller-link" onclick="openSeller(decodeURIComponent('${encodeURIComponent(s)}'))">${esc(s)}</button></td><td>${fmt(c.rev)}</td><td>${(c.rev/total*100).toLocaleString('pt-BR',{maximumFractionDigits:1})}%</td><td>${fmt(ma.rev)}</td><td class="${c.rev-ma.rev>=0?'positive':'negative'}">${fmt(c.rev-ma.rev)}</td><td>${growthHtml(growth(c.rev,ma.rev))}</td><td>${fmt(aa.rev)}</td><td class="${c.rev-aa.rev>=0?'positive':'negative'}">${fmt(c.rev-aa.rev)}</td><td>${growthHtml(growth(c.rev,aa.rev))}</td><td>${fmt(c.ticket)}</td></tr>`}).join('');const cur=sum(allCurrent),ma=sum(rowsForMonth(p.previous,'',p.dayLimit)),aa=sum(rowsForMonth(p.previousYear,'',p.dayLimit)),orders=unique(allCurrent,'order');el('comparisonBody').innerHTML=(body||'<tr><td colspan="10" class="empty">Sem dados</td></tr>')+(body?`<tr><td><b>Total</b></td><td><b>${fmt(cur)}</b></td><td>100%</td><td>${fmt(ma)}</td><td class="${cur-ma>=0?'positive':'negative'}">${fmt(cur-ma)}</td><td>${growthHtml(growth(cur,ma))}</td><td>${fmt(aa)}</td><td class="${cur-aa>=0?'positive':'negative'}">${fmt(cur-aa)}</td><td>${growthHtml(growth(cur,aa))}</td><td>${fmt(orders?cur/orders:0)}</td></tr>`:'')}
function openSeller(seller){openDetails(baseRows().filter(r=>r.seller===seller),`Vendedor: ${seller}`)}
function renderHistory(){const base=baseRows(),months=[...new Set(base.map(r=>r.month).filter(Boolean))].sort(),sellers=[...new Set(base.map(r=>r.seller).filter(Boolean))].sort(),head='<th>Vendedor</th>'+months.map(m=>`<th>${m.slice(5)}/${m.slice(2,4)}</th>`).join('')+'<th>Total</th>';let body='';sellers.forEach((seller,i)=>{const rr=base.filter(r=>r.seller===seller),clients=[...new Set(rr.map(r=>r.buyer).filter(Boolean))].sort(),id='hist-'+i;body+=`<tr><td><button class="toggle" onclick="toggleHistory('${id}',this)">+</button> ${esc(seller)}</td>${months.map(m=>`<td>${short(sum(rr.filter(r=>r.month===m)))}</td>`).join('')}<td><b>${short(sum(rr))}</b></td></tr>`;clients.forEach(client=>{const cr=rr.filter(r=>r.buyer===client);body+=`<tr class="history-client group-${id}"><td><button class="client-link" onclick="openClient(decodeURIComponent('${encodeURIComponent(client)}'))">↳ ${esc(client)}</button></td>${months.map(m=>`<td>${short(sum(cr.filter(r=>r.month===m)))}</td>`).join('')}<td><b>${short(sum(cr))}</b></td></tr>`})});el('historyWrap').innerHTML=`<table class="history-table"><thead><tr>${head}</tr></thead><tbody>${body||'<tr><td class="empty">Sem dados</td></tr>'}</tbody></table>`}
function toggleHistory(id,button){const rr=document.querySelectorAll('.group-'+id),open=!rr[0]?.classList.contains('open');rr.forEach(r=>r.classList.toggle('open',open));button.textContent=open?'−':'+'}
function renderMap(data){if(!window.L)return;if(!leafletMap){leafletMap=L.map('revenueMap',{zoomControl:true,scrollWheelZoom:true}).setView([-14.2,-51.9],4);L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:18,subdomains:'abcd',attribution:'© OpenStreetMap © CARTO'}).addTo(leafletMap);leafletLayer=L.layerGroup().addTo(leafletMap)}leafletLayer.clearLayers();const map={};data.forEach(r=>{if(UF_COORDS[r.state])map[r.state]=(map[r.state]||0)+r.revenue});const max=Math.max(...Object.values(map),1);Object.entries(map).forEach(([uf,val])=>{const [lat,lng]=UF_COORDS[uf];L.circleMarker([lat,lng],{radius:6+(val/max)*22,fillColor:'#2D70B8',color:'#36E2C9',weight:1.5,fillOpacity:.65}).bindTooltip(`${uf}: ${fmt(val)}`).addTo(leafletLayer)});setTimeout(()=>leafletMap.invalidateSize(),100)}
function renderTop(data){const configs=[['buyer',el('clientTable'),false],['family',el('familyTable'),false],['product',el('productTable'),true]];configs.forEach(([key,body,isProduct])=>{const list=aggregate(data,key).slice(0,10);body.innerHTML=list.length?list.map(([name,z])=>`<tr><td>${key==='buyer'?`<button class="client-link" onclick="openClient(decodeURIComponent('${encodeURIComponent(name)}'))">${esc(name)}</button>`:esc(name)}</td><td>${short(z.value)}</td><td>${isProduct?z.units.toLocaleString('pt-BR',{maximumFractionDigits:0}):z.orders.size}</td></tr>`).join(''):'<tr><td colspan="3" class="empty">Sem dados</td></tr>'})}
function renderDetail(list,body,prefix){const groups=new Map();list.forEach(r=>{if(!groups.has(r.buyer))groups.set(r.buyer,[]);groups.get(r.buyer).push(r)});body.innerHTML=groups.size?[...groups.entries()].sort((a,b)=>sum(b[1])-sum(a[1])).map(([client,rr],i)=>{const id=`${prefix}-${i}`,total=sum(rr),units=rr.reduce((s,r)=>s+r.units,0),orders=unique(rr,'order');const details=rr.map(r=>`<tr class="product-row group-${id}"><td></td><td>${esc(r.product)}</td><td>${r.group}</td><td>${esc(r.seller)}</td><td>${esc(r.channel)}</td><td>${esc(r.order||'—')}</td><td>${esc(r.status)}</td><td>${dateBR(r.date)}</td><td>${r.units.toLocaleString('pt-BR',{maximumFractionDigits:2})}</td><td>${fmt(r.revenue)}</td></tr>`).join('');return`<tr class="client-row"><td><button class="toggle" onclick="toggleGroup('${id}',this)">+</button></td><td><button class="client-link" onclick="openClient(decodeURIComponent('${encodeURIComponent(client)}'))">${esc(client)}</button></td><td>${[...new Set(rr.map(r=>r.group))].join(', ')}</td><td>${esc([...new Set(rr.map(r=>r.seller))].join(', '))}</td><td>${esc([...new Set(rr.map(r=>r.channel))].join(', '))}</td><td>${orders}</td><td>—</td><td>—</td><td>${units.toLocaleString('pt-BR',{maximumFractionDigits:2})}</td><td>${fmt(total)}</td></tr>${details}`}).join(''):'<tr><td colspan="10" class="empty">Nenhum registro encontrado.</td></tr>'}
function toggleGroup(id,button){const rr=document.querySelectorAll('.group-'+id),open=!rr[0]?.classList.contains('open');rr.forEach(r=>r.classList.toggle('open',open));button.textContent=open?'−':'+'}
function openClient(client){openDetails(baseRows().filter(r=>r.buyer===client),`Cliente: ${client}`)}
function openDetails(list,title){el('modalTitle').textContent=title;el('modalValue').textContent=fmt(sum(list));el('modalOrders').textContent=unique(list,'order');el('modalClients').textContent=unique(list,'buyer');el('modalUnits').textContent=list.reduce((s,r)=>s+r.units,0).toLocaleString('pt-BR',{maximumFractionDigits:0});renderDetail(list,el('modalBody'),'modal');el('statusModal').classList.add('show')}
function populate(){const months=[...new Set(rows.map(r=>r.month).filter(Boolean))].sort().reverse(),current=`${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,'0')}`;el('monthFilter').innerHTML='<option value="">Todos os meses</option>'+months.map(m=>`<option value="${m}">${monthName(m)}</option>`).join('');selectedMonth=months.includes(current)?current:(months[0]||'');el('monthFilter').value=selectedMonth;const channels=[...new Set(rows.map(r=>r.channel).filter(Boolean))].sort(),sellers=[...new Set(rows.map(r=>r.seller).filter(Boolean))].sort();el('channelFilter').innerHTML='<option value="">Todos</option>'+channels.map(v=>`<option>${esc(v)}</option>`).join('');el('sellerFilter').innerHTML='<option value="">Todos</option>'+sellers.map(v=>`<option>${esc(v)}</option>`).join('')}
function bind(){document.querySelectorAll('[data-group]').forEach(b=>b.addEventListener('click',()=>{selectedGroup=b.dataset.group;selectedSeller=selectedChannel='';el('sellerFilter').value=el('channelFilter').value='';document.querySelectorAll('[data-group]').forEach(x=>x.classList.toggle('active',x===b));el('groupBadge').textContent=selectedGroup==='ALL'?'Grupo UUIZZ':selectedGroup;render()}));el('monthFilter').addEventListener('change',e=>{selectedMonth=e.target.value;dateFrom=dateTo='';el('dateFrom').value=el('dateTo').value='';render()});el('dateFrom').addEventListener('change',e=>{dateFrom=e.target.value;selectedMonth='';el('monthFilter').value='';render()});el('dateTo').addEventListener('change',e=>{dateTo=e.target.value;selectedMonth='';el('monthFilter').value='';render()});el('channelFilter').addEventListener('change',e=>{selectedChannel=e.target.value;render()});el('sellerFilter').addEventListener('change',e=>{selectedSeller=e.target.value;render()});el('searchClient').addEventListener('input',e=>{searchClient=e.target.value;render()});el('searchProduct').addEventListener('input',e=>{searchProduct=e.target.value;render()});el('clearDates').addEventListener('click',()=>{dateFrom=dateTo='';el('dateFrom').value=el('dateTo').value='';render()});el('capturedCard').addEventListener('click',()=>openDetails(visibleRows(),'Receita Captada'));el('modalClose').addEventListener('click',()=>el('statusModal').classList.remove('show'));el('statusModal').addEventListener('click',e=>{if(e.target===el('statusModal'))el('statusModal').classList.remove('show')})}
async function logout(){await sb.auth.signOut();location.href='index.html'}
async function init(){const {data:{session}}=await sb.auth.getSession();if(!session){location.href='index.html';return}currentUser=session.user;const email=(currentUser.email||'').toLowerCase();if(RESTRICTED.includes(email)){location.replace('painel.html');return}if(!(email.endsWith('@gpsbi.com.br')||email==='daniela@empoderamentoadolescente.com.br')){location.href='index.html';return}const eaCw=(window.UUIZZ_GROUP_COMMERCIAL_DATA||[]).map(toRecord).filter(r=>r.group==='EA'||r.group==='CW'),mw=(window.MISTER_WIZ_COMMERCIAL_DATA||[]).map(toMwRecord).filter(Boolean);rows=[...eaCw,...mw];renderAppNav({activePage:'painelgrupo.html',userLabel:email.split('@')[0]||'Usuário',userRole:'owner',onLogout:logout,sb,currentUser});populate();const requested=(new URLSearchParams(location.search).get('grupo')||'').toUpperCase();if(requested==='EA'||requested==='CW')selectedGroup=requested;bind();document.querySelectorAll('[data-group]').forEach(b=>b.classList.toggle('active',b.dataset.group===selectedGroup));el('groupBadge').textContent=selectedGroup==='ALL'?'Grupo UUIZZ':selectedGroup;el('loadingScreen').style.display='none';el('mainContent').style.display='block';render()}
init();
