-- HUB DOMINE · GPSBI
create table if not exists public.comunicados_domine (id bigint generated by default as identity primary key, titulo text not null, conteudo text not null, fixado boolean default false, criado_por uuid references auth.users(id), created_at timestamptz default now());
create table if not exists public.tarefas_domine (id bigint generated by default as identity primary key, usuario_id uuid references auth.users(id), titulo text not null, data date, status text default 'pendente', created_at timestamptz default now());
create table if not exists public.aprovacoes_domine (id bigint generated by default as identity primary key, solicitante_id uuid references auth.users(id), tipo text not null, justificativa text, status text default 'pendente', created_at timestamptz default now());
alter table public.comunicados_domine enable row level security; alter table public.tarefas_domine enable row level security; alter table public.aprovacoes_domine enable row level security;
create policy "authenticated read comunicados" on public.comunicados_domine for select to authenticated using (true);
create policy "own tarefas" on public.tarefas_domine for all to authenticated using (usuario_id=auth.uid()) with check (usuario_id=auth.uid());
create policy "own aprovacoes" on public.aprovacoes_domine for select to authenticated using (solicitante_id=auth.uid());